let q_set1 = {
    "Doktor mana penjahat tarik?"             : "A",
    "Siapa budak lelaki tolak?"               : "B",
    "Budak lelaki mana marah datuk?"          : "B",
    "Siapa buli lelaki tinggi?"               : "A",
    "Wanita mana nenek simbah air?"           : "A",
    "Siapa ayah tarik telinga?"               : "B",
    "Pengurus mana tendang budak lelaki?"     : "B",
    "Siapa lukis budak lelaki?"               : "A",
    "Datuk mana budak lelaki selamatkan?"     : "A",
    "Siapa budak perempuan tengking?"         : "B",
    "Siapa pujuk budak lelaki?"               : "B",
    "Datuk mana orang buta bantu?"            : "A",
    "Siapa budak lelaki kejutkan?"            : "A",
    "Budak lelaki mana gigit datuk?"          : "A",
    "Siapa tarik doktor?"                     : "B",
    "Budak lelaki mana pengurus dendam?"      : "B",
    "Siapa guru ajar?"                        : "A",
    "Budak lelaki mana tuduh pengurus?"       : "A",
    "Siapa sapa wanita?"                      : "B",
    "Penjahat mana tembak pengurus?"          : "A",
    "Ibu mana budak perempuan cium?"          : "B",
    "Siapa datuk hiburkan?"                   : "B",
    "Budak perempuan mana ketuk nenek?"       : "B",
    "Siapa suap ibu?"                         : "A",
    "Budak lelaki mana pemuda ambil gambar?"  : "A",
    "Siapa datuk panggil?"                    : "B",
    "Ibu mana bebel budak perempuan?"         : "B",
    "Siapa dukung pengurus?"                  : "A",
    "Doktor mana tentera pijak?"              : "A",
    "Siapa ibu peluk?"                        : "A",
    "Siapa kejar penjahat?"                   : "B",
    "Pemuda mana budak lelaki tolak?"         : "B",
    "Siapa budak pendek usik?"                : "A",
    "Budak perempuan mana hayun ibu?"         : "A",
    "Siapa tangkap polis?"                    : "B",
    "Bayi mana ibu cubit?"                    : "A",
    "Siapa budak lelaki mandikan?"            : "A",
    "Budak perempuan mana urut ibu?"          : "A",
    "Siapa kejar datuk?"                      : "B",
    "Budak lelaki mana siram abang?"          : "A"
}

let q_set2 = {
    "Siapa tarik penjahat?"                   : "B",
    "Datuk mana budak lelaki tolak?"          : "B",
    "Siapa datuk marah?"                      : "A",
    "Lelaki pendek mana buli lelaki tinggi?"  : "A",
    "Siapa simbah nenek?"                     : "B",
    "Budak lelaki mana ayah tarik telinga?"   : "B",
    "Siapa budak lelaki tendang?"             : "A",
    "Datuk mana lukis budak lelaki?"          : "A",
    "Siapa selamatkan budak lelaki?"          : "B",
    "Nenek mana tengking budak perempuan?"    : "A",
    "Pengurus mana budak lelaki pujuk?"       : "A",
    "Siapa orang buta bantu?"                 : "B",
    "Pak cik mana kejutkan budak lelaki?"     : "B",
    "Siapa gigit datuk?"                      : "A",
    "Polis mana doktor tarik?"                : "A",
    "Siapa pengurus dendam?"                  : "B",
    "Budak perempuan mana ajar guru?"         : "B",
    "Siapa tuduh pengurus?"                   : "A",
    "Budak perempuan mana wanita sapa?"       : "A",
    "Siapa pengurus tembak?"                  : "B",
    "Siapa cium budak perempuan?"             : "B",
    "Budak lelaki mana datuk hiburkan?"       : "B",
    "Siapa nenek ketuk?"                      : "A",
    "Budak perempuan mana suap ibu?"          : "A",
    "Siapa ambil gambar pemuda?"              : "B",
    "Budak lelaki mana datuk panggil?"        : "B",
    "Siapa budak perempuan bebel?"            : "A",
    "Datuk mana dukung pengurus?"             : "A",
    "Siapa pijak tentera?"                    : "B",
    "Budak perempuan mana peluk ibu?"         : "A",
    "Polis mana penjahat kejar?"              : "B",
    "Siapa budak lelaki tolak?"               : "B",
    "Budak tinggi mana usik budak pendek?"    : "B",
    "Siapa hayunkan ibu?"                     : "A",
    "Penjahat mana polis tangkap?"            : "A",
    "Siapa ibu cubit?"                        : "B",
    "Ayah mana mandikan budak lelaki?"        : "B",
    "Siapa urut ibu?"                         : "A",
    "Budak lelaki mana datuk kejar?"          : "A",
    "Siapa abang siram?"                      : "B"
}

let q_set3 = {
    "Doktor mana tarik penjahat?"             : "B",
    "Siapa tolak budak lelaki?"               : "A",
    "Budak lelaki mana datuk marah?"          : "A",
    "Siapa lelaki tinggi buli?"               : "B",
    "Wanita mana simbah nenek?"               : "B",
    "Siapa tarik telinga ayah?"               : "A",
    "Pengurus mana budak lelaki tendang?"     : "A",
    "Siapa budak lelaki lukis?"               : "B",
    "Datuk mana selamatkan budak lelaki?"     : "B",
    "Siapa tengking budak perempuan?"         : "A",
    "Siapa budak lelaki pujuk?"               : "A",
    "Datuk mana bantu orang buta?"            : "B",
    "Siapa kejutkan budak lelaki?"            : "B",
    "Budak lelaki mana datuk gigit?"          : "B",
    "Siapa doktor tarik?"                     : "A",
    "Budak lelaki mana dendam pengurus?"      : "A",
    "Siapa ajar guru?"                        : "B",
    "Budak lelaki mana pengurus tuduh?"       : "B",
    "Siapa wanita sapa?"                      : "A",
    "Penjahat mana pengurus tembak?"          : "B",
    "Ibu mana cium budak perempuan?"          : "B",
    "Siapa hiburkan datuk?"                   : "A",
    "Budak perempuan mana nenek ketuk?"       : "A",
    "Siapa ibu suap?"                         : "B",
    "Budak lelaki mana ambil gambar pemuda?"  : "B",
    "Siapa panggil datuk?"                    : "A",
    "Ibu mana budak perempuan bebel?"         : "A",
    "Siapa pengurus dukung?"                  : "B",
    "Doktor mana pijak tentera?"              : "B",
    "Siapa peluk ibu?"                        : "A",
    "Siapa penjahat kejar?"                   : "A",
    "Pemuda mana tolak budak lelaki?"         : "A",
    "Siapa usik budak pendek?"                : "B",
    "Budak perempuan mana ibu hayunkan?"      : "B",
    "Siapa polis tangkap?"                    : "A",
    "Bayi mana cubit ibu?"                    : "A",
    "Siapa mandikan budak lelaki?"            : "B",
    "Budak perempuan mana ibu urut?"          : "B",
    "Siapa datuk kejar?"                      : "A",
    "Budak lelaki mana abang siram?"          : "A"
}

let q_set4 = {
    "Siapa penjahat tarik?"                   : "A",
    "Datuk mana tolak budak lelaki?"          : "A",
    "Siapa marah datuk?"                      : "B",
    "Lelaki pendek mana lelaki tinggi buli?"  : "B",
    "Siapa nenek simbah?"                     : "A",
    "Budak lelaki mana tarik telinga ayah?"   : "A",
    "Siapa tendang budak lelaki?"             : "B",
    "Datuk mana budak lelaki lukis?"          : "B",
    "Siapa budak lelaki selamatkan?"          : "A",
    "Nenek mana budak perempuan tengking?"    : "B",
    "Pengurus mana pujuk budak lelaki?"       : "B",
    "Siapa bantu orang buta?"                 : "B",
    "Pak cik mana budak lelaki kejutkan?"     : "A",
    "Siapa datuk gigit?"                      : "B",
    "Polis mana tarik doktor?"                : "B",
    "Siapa dendam pengurus?"                  : "A",
    "Budak perempuan mana guru ajar?"         : "A",
    "Siapa pengurus tuduh?"                   : "A",
    "Budak perempuan mana sapa wanita?"       : "B",
    "Siapa tembak pengurus?"                  : "A",
    "Siapa budak perempuan cium?"             : "A",
    "Budak lelaki mana hiburkan datuk?"       : "A",
    "Siapa ketuk nenek?"                      : "B",
    "Budak perempuan mana ibu suap?"          : "B",
    "Siapa pemuda ambil gambar?"              : "A",
    "Budak lelaki mana panggil datuk?"        : "A",
    "Siapa bebel budak perempuan?"            : "B",
    "Datuk mana pengurus dukung?"             : "A",
    "Siapa tentera pijak?"                    : "A",
    "Budak perempuan mana ibu peluk?"         : "B",
    "Polis mana kejar penjahat?"              : "B",
    "Siapa tolak budak lelaki?"               : "A",
    "Budak tinggi mana budak pendek usik?"    : "A",
    "Siapa ibu hayunkan?"                     : "B",
    "Penjahat mana tangkap polis?"            : "B",
    "Siapa cubit ibu?"                        : "A",
    "Ayah mana budak lelaki mandikan?"        : "A",
    "Siapa ibu urut?"                         : "A",
    "Budak lelaki mana kejar datuk?"          : "B",
    "Siapa siram abang?"                      : "A"
}